### ISSUE TITLE
Error on Klipper startup 

### ISSUE THREAD

**Issue by joseph-greiner** [viesturz/NozzleAlign#1] opened 2023-09-22 22:00 UTC
Tried to install this, received the following error:
![image](https://github.com/viesturz/NozzleAlign/assets/11715110/a5549742-47f6-4941-aa92-a071a431e8ce)

I tried commenting out [probe] sections in my config, but the same error appears.
I tried adding the other module files under the tap changer repo.

Here is the klipper log file if it helps. I think this would be very useful on my printer, especially after seeing the video about it.
Do I need to be on a specific branch of Klipper for it to work? 

[klippy.log](https://github.com/viesturz/NozzleAlign/files/12704844/klippy.log)

**Comment by viesturz** [comment] 2023-09-23 07:32
Hi, nozzle align relies on a bed probe being present in your config.
It's used for the probe offset calculation. 
It looks like the issue is that probe is defined after [tools_calibrate] in your config. Moving it up should fix.
I'm updating the code so that it does not matter.

**Comment by viesturz** [comment] 2023-09-23 07:42
Updated to make the [probe] access entirely optional, only when you call TOOL_CALIBRATE_PROBE_OFFSET

**Closed by viesturz** 2023-09-23 07:42 UTC

**Comment by joseph-greiner** [comment] 2023-09-23 19:02
Thank you, I usually put my [include] at the top of the file (old habits). I re-downloaded and tried this, I got the same error. I moved [include calibrate-offsets.cfg] to below the [probe] section and I no longer get startup errors.
